prebuilt_cxx_library(
  name = 'dl', 
  header_only = True, 
  exported_linker_flags = [
    '-ldl', 
  ], 
)

prebuilt_cxx_library(
  name = 'pthread', 
  header_only = True, 
  exported_linker_flags = [
    '-lpthread', 
  ], 
)

cxx_library(
  name = 'sqlite3', 
  header_namespace = '', 
  exported_headers = [
    'sqlite3.h', 
  ], 
  srcs = [
    'sqlite3.c', 
  ], 
  platform_deps = [
    ('linux.*', [ ':dl', ':pthread' ]), 
  ],
  visibility = [
    'PUBLIC', 
  ], 
)
